FROM golang:1.3-cross
ADD . /go/src/github.com/t0mk/bitbucket-jenkins-proxy
WORKDIR /go/src/github.com/t0mk/bitbucket-jenkins-proxy
ENV GOOS linux
ENV GOARCH amd64
RUN go get
RUN chmod +x /go/src/github.com/t0mk/bitbucket-jenkins-proxy/make.sh
ENTRYPOINT ["/go/src/github.com/t0mk/bitbucket-jenkins-proxy/make.sh"]
